#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from vrc_ardy_agent.three_point_bridge import iter_three_point_frames, replay_three_point_frames


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay ARDY head + both hands into VRto3D and VMT.")
    parser.add_argument("npz", type=Path, help="ARDY .npz generated by scripts/generate.py")
    parser.add_argument("--host", required=True, help="Windows host running VRto3D and VMT")
    parser.add_argument("--opentrack-port", type=int, default=4242, help="VRto3D OpenTrack UDP port")
    parser.add_argument("--vmt-port", type=int, default=39570, help="VMT OSC UDP port")
    parser.add_argument("--head-index", type=int, default=6, help="ARDY Head index on Core27")
    parser.add_argument("--left-index", type=int, default=16, help="ARDY LeftHand index on Core27")
    parser.add_argument("--right-index", type=int, default=10, help="ARDY RightHand index on Core27")
    parser.add_argument("--left-vmt-index", type=int, default=1, help="VMT left controller index")
    parser.add_argument("--right-vmt-index", type=int, default=2, help="VMT right controller index")
    parser.add_argument("--left-enable", type=int, default=5, help="VMT left Index-compatible mode")
    parser.add_argument("--right-enable", type=int, default=6, help="VMT right Index-compatible mode")
    parser.add_argument(
        "--hmd-base",
        type=float,
        nargs=3,
        metavar=("X", "Y", "Z"),
        default=(0.0, 1.0, 0.0),
        help="VRto3D base HMD position in SteamVR room meters",
    )
    parser.add_argument("--scale", type=float, default=1.0, help="Scale ARDY offsets around the initial head")
    parser.add_argument("--loops", type=int, default=1, help="Number of times to replay the motion")
    parser.add_argument("--dry-run", action="store_true", help="Parse and pace frames without sending UDP")
    parser.add_argument(
        "--park-head-on-exit",
        action="store_true",
        help="Send neutral OpenTrack pose after the final loop",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.loops < 1:
        raise SystemExit("--loops must be at least 1")

    target = "dry-run" if args.dry_run else args.host
    print(
        "three-point replay "
        f"{args.npz} -> head:{target}:{args.opentrack_port}, "
        f"left:VMT_{args.left_vmt_index}, right:VMT_{args.right_vmt_index}",
        flush=True,
    )

    total = 0
    for loop_idx in range(args.loops):
        frames = iter_three_point_frames(
            args.npz,
            head_index=args.head_index,
            left_index=args.left_index,
            right_index=args.right_index,
            hmd_base=tuple(args.hmd_base),
            scale=args.scale,
        )
        sent = replay_three_point_frames(
            frames,
            host=args.host,
            opentrack_port=args.opentrack_port,
            vmt_port=args.vmt_port,
            left_tracker_index=args.left_vmt_index,
            right_tracker_index=args.right_vmt_index,
            left_enable=args.left_enable,
            right_enable=args.right_enable,
            dry_run=args.dry_run,
            park_head_on_exit=args.park_head_on_exit and loop_idx == args.loops - 1,
        )
        total += sent
        print(f"loop {loop_idx + 1}/{args.loops}: {sent} frames", flush=True)

    print(f"done: {total} synchronized frames", flush=True)


if __name__ == "__main__":
    main()