#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from vrc_ardy_agent.six_point_bridge import iter_six_point_frames, replay_six_point_frames


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay ARDY 6-point tracking into VRto3D and VMT.")
    parser.add_argument("npz", type=Path, help="ARDY .npz generated by scripts/generate.py")
    parser.add_argument("--host", required=True, help="Windows host running VRto3D and VMT")
    parser.add_argument("--opentrack-port", type=int, default=4242, help="VRto3D OpenTrack UDP port")
    parser.add_argument("--vmt-port", type=int, default=39570, help="VMT OSC UDP port")
    parser.add_argument("--vrchat-port", type=int, default=9000, help="VRChat OSC input UDP port")
    parser.add_argument("--head-index", type=int, default=6)
    parser.add_argument("--left-index", type=int, default=16)
    parser.add_argument("--right-index", type=int, default=10)
    parser.add_argument("--hips-index", type=int, default=0)
    parser.add_argument("--left-foot-index", type=int, default=25)
    parser.add_argument("--right-foot-index", type=int, default=21)
    parser.add_argument("--left-toe-index", type=int, default=26)
    parser.add_argument("--right-toe-index", type=int, default=22)
    parser.add_argument("--left-vmt-index", type=int, default=1)
    parser.add_argument("--right-vmt-index", type=int, default=2)
    parser.add_argument("--hips-vmt-index", type=int, default=3)
    parser.add_argument("--left-foot-vmt-index", type=int, default=4)
    parser.add_argument("--right-foot-vmt-index", type=int, default=5)
    parser.add_argument("--left-enable", type=int, default=5)
    parser.add_argument("--right-enable", type=int, default=6)
    parser.add_argument("--body-enable", type=int, default=7, help="VMT compatible tracker mode")
    parser.add_argument("--full-stick-speed-mps", type=float, default=2.5, help="ARDY root speed that maps to full joystick deflection")
    parser.add_argument("--locomotion-deadzone-mps", type=float, default=0.08, help="Ignore smaller horizontal root speeds")
    parser.add_argument("--full-turn-speed-dps", type=float, default=180.0, help="ARDY root yaw speed that maps to full LookHorizontal input")
    parser.add_argument("--turn-deadzone-dps", type=float, default=12.0, help="Ignore smaller root yaw speeds")
    parser.add_argument("--heading-smoothing-seconds", type=float, default=0.5, help="Temporal smoothing window for ARDY root heading")
    parser.add_argument("--no-locomotion", action="store_true", help="Do not convert ARDY root motion into VRChat OSC movement input")
    parser.add_argument(
        "--hmd-base",
        type=float,
        nargs=3,
        metavar=("X", "Y", "Z"),
        default=(0.0, 1.0, 0.0),
        help="VRto3D base HMD room position in meters",
    )
    parser.add_argument(
        "--scale",
        type=float,
        default=None,
        help="Explicit body scale. Omit to fit ARDY head-to-floor height to the HMD base height.",
    )
    parser.add_argument("--loops", type=int, default=1)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--park-head-on-exit", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.loops < 1:
        raise SystemExit("--loops must be at least 1")

    target = "dry-run" if args.dry_run else args.host
    print(
        "six-point replay "
        f"{args.npz} -> head:{target}:{args.opentrack_port}, "
        f"L:VMT_{args.left_vmt_index}, R:VMT_{args.right_vmt_index}, "
        f"hips:VMT_{args.hips_vmt_index}, LF:VMT_{args.left_foot_vmt_index}, RF:VMT_{args.right_foot_vmt_index}, "
        f"locomotion={'off' if args.no_locomotion else f'VRChat:{args.vrchat_port}'}",
        flush=True,
    )

    total = 0
    for loop_idx in range(args.loops):
        frames = iter_six_point_frames(
            args.npz,
            head_index=args.head_index,
            left_index=args.left_index,
            right_index=args.right_index,
            hips_index=args.hips_index,
            left_foot_index=args.left_foot_index,
            right_foot_index=args.right_foot_index,
            left_toe_index=args.left_toe_index,
            right_toe_index=args.right_toe_index,
            hmd_base=tuple(args.hmd_base),
            scale=args.scale,
            locomotion=not args.no_locomotion,
            full_stick_speed_mps=args.full_stick_speed_mps,
            locomotion_deadzone_mps=args.locomotion_deadzone_mps,
            full_turn_speed_dps=args.full_turn_speed_dps,
            turn_deadzone_dps=args.turn_deadzone_dps,
            heading_smoothing_seconds=args.heading_smoothing_seconds,
        )
        sent = replay_six_point_frames(
            frames,
            host=args.host,
            opentrack_port=args.opentrack_port,
            vmt_port=args.vmt_port,
            left_tracker_index=args.left_vmt_index,
            right_tracker_index=args.right_vmt_index,
            hips_tracker_index=args.hips_vmt_index,
            left_foot_tracker_index=args.left_foot_vmt_index,
            right_foot_tracker_index=args.right_foot_vmt_index,
            left_enable=args.left_enable,
            right_enable=args.right_enable,
            body_enable=args.body_enable,
            send_locomotion=not args.no_locomotion,
            vrchat_port=args.vrchat_port,
            dry_run=args.dry_run,
            park_head_on_exit=args.park_head_on_exit and loop_idx == args.loops - 1,
        )
        total += sent
        if loop_idx == 0:
            # Scale is stable for a given NPZ; report it once for debugging.
            first_frame = next(
                iter_six_point_frames(
                    args.npz,
                    head_index=args.head_index,
                    left_index=args.left_index,
                    right_index=args.right_index,
                    hips_index=args.hips_index,
                    left_foot_index=args.left_foot_index,
                    right_foot_index=args.right_foot_index,
                    left_toe_index=args.left_toe_index,
                    right_toe_index=args.right_toe_index,
                    hmd_base=tuple(args.hmd_base),
                    scale=args.scale,
                    locomotion=not args.no_locomotion,
                    full_stick_speed_mps=args.full_stick_speed_mps,
                    locomotion_deadzone_mps=args.locomotion_deadzone_mps,
                    full_turn_speed_dps=args.full_turn_speed_dps,
                    turn_deadzone_dps=args.turn_deadzone_dps,
                    heading_smoothing_seconds=args.heading_smoothing_seconds,
                )
            )
            print(f"resolved scale: {first_frame.scale:.4f}", flush=True)
        print(f"loop {loop_idx + 1}/{args.loops}: {sent} frames", flush=True)

    print(f"done: {total} synchronized frames", flush=True)


if __name__ == "__main__":
    main()