#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from vrc_ardy_agent.opentrack_bridge import iter_opentrack_frames, replay_frames


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay an ARDY head joint into VRto3D via OpenTrack UDP.")
    parser.add_argument("npz", type=Path, help="ARDY .npz generated by scripts/generate.py")
    parser.add_argument("--host", required=True, help="Windows host running VRto3D")
    parser.add_argument("--port", type=int, default=4242, help="VRto3D OpenTrack UDP port")
    parser.add_argument("--joint-index", type=int, default=6, help="ARDY joint index; 6 = Head on Core27")
    parser.add_argument("--loops", type=int, default=1, help="Number of times to replay the motion")
    parser.add_argument("--dry-run", action="store_true", help="Parse and pace frames without sending UDP")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.loops < 1:
        raise SystemExit("--loops must be at least 1")

    mode = "dry-run" if args.dry_run else f"{args.host}:{args.port}"
    print(f"replaying {args.npz} head joint={args.joint_index} -> OpenTrack {mode}", flush=True)

    total = 0
    for loop_idx in range(args.loops):
        frames = iter_opentrack_frames(args.npz, joint_index=args.joint_index)
        sent = replay_frames(frames, host=args.host, port=args.port, dry_run=args.dry_run)
        total += sent
        print(f"loop {loop_idx + 1}/{args.loops}: {sent} frames", flush=True)
    print(f"done: {total} frames", flush=True)


if __name__ == "__main__":
    main()