#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from vrc_ardy_agent.vmt_bridge import iter_vmt_frames, replay_frames


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay an ARDY joint into a VMT tracker over OSC/UDP.")
    parser.add_argument("npz", type=Path, help="ARDY .npz generated by scripts/generate.py")
    parser.add_argument("--host", required=True, help="Windows host running VMT")
    parser.add_argument("--port", type=int, default=39570, help="VMT OSC receive port")
    parser.add_argument("--joint-index", type=int, default=10, help="ARDY joint index; 10 = RightHand on Core27")
    parser.add_argument("--tracker-index", type=int, default=0, help="VMT device index")
    parser.add_argument(
        "--enable",
        type=int,
        default=1,
        choices=range(0, 8),
        metavar="MODE",
        help="VMT enable/device mode (6 = right Index-compatible controller)",
    )
    parser.add_argument("--scale", type=float, default=1.0, help="Position scale")
    parser.add_argument("--loops", type=int, default=1, help="Number of times to replay the motion")
    parser.add_argument(
        "--offset",
        type=float,
        nargs=3,
        metavar=("X", "Y", "Z"),
        default=(0.0, 0.0, 0.0),
        help="Room-space position offset in meters",
    )
    parser.add_argument("--dry-run", action="store_true", help="Parse and pace frames without sending UDP")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.loops < 1:
        raise SystemExit("--loops must be at least 1")
    mode = "dry-run" if args.dry_run else f"{args.host}:{args.port}"
    print(
        f"replaying {args.npz} joint={args.joint_index} -> VMT_{args.tracker_index} {mode}",
        flush=True,
    )
    total = 0
    for loop_idx in range(args.loops):
        frames = iter_vmt_frames(args.npz, joint_index=args.joint_index)
        sent = replay_frames(
            frames,
            host=args.host,
            port=args.port,
            tracker_index=args.tracker_index,
            enable=args.enable,
            scale=args.scale,
            offset=tuple(args.offset),
            dry_run=args.dry_run,
        )
        total += sent
        print(f"loop {loop_idx + 1}/{args.loops}: {sent} frames", flush=True)
    print(f"done: {total} frames", flush=True)


if __name__ == "__main__":
    main()